---
Name: approutes
After:
  - '#rootroutes'
  - '#coreroutes'
---
SilverStripe\Control\Director:
  rules:
    activation: App\Web\Layout\ActivationController
    one-off-pass: App\Web\Layout\OneoffPassController
    we-auth : 'KSolution\Controller\WeAuthController'
    signin : 'KSolution\Controller\SigninController'
    signup : 'KSolution\Controller\SignupController'
    signout : 'KSolution\Controller\SignoutController'
    'promo-handler/$hash': 'KSolution\Controller\PromoHandler'
    'api/v1/signup' : 'Leochenftw\API\SignupAPI'
    'api/v1/signin' : 'Leochenftw\API\SigninAPI'
    'api/v1/signout' : 'Leochenftw\API\SignoutAPI'
    'api/v1/recovery' : 'Leochenftw\API\RecoveryAPI'
    'api/v1/session' : 'Leochenftw\API\SessionAPI'
    'api/v1/member/$action' : 'Leochenftw\API\MemberAPI'
    member/$action: 'App\Web\Layout\MemberCentreController'
    'api/v1/photo/$ID/$Action' : 'Leochenftw\API\PhotoAPI'
    'api/v1/video/$ID/$Action' : 'Leochenftw\API\VideoAPI'
    'api/v1/password/$Action' : 'Leochenftw\API\PasswordAPI'
    'api/v1/dog/$ID/$Action' : 'Leochenftw\API\DogAPI'
    'api/v1/dog-lookup' : 'Leochenftw\API\DogLookupAPI'
